#!/usr/bin/env python3
"""
Kohya Training Config Generator
================================

Generates TOML configuration files for Kohya sd-scripts LoRA training.
Automatically calculates optimal parameters based on dataset size and hardware.

Supports:
- SDXL LoRA training (1024x1024)
- SD 1.5 LoRA training (512x512)
- Automatic repeat calculation
- Memory-optimized settings

Usage:
    python generate_kohya_config.py \
        --dataset-dir /path/to/training_data \
        --output-config /path/to/config.toml \
        --character-name luca \
        --model-type sdxl

Author: LLMProvider Tooling
Date: 2025-12-07
"""

import argparse
import json
import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional


@dataclass
class TrainingParams:
    """Training parameters based on dataset analysis"""
    num_images: int
    total_steps: int
    num_epochs: int
    repeats: int
    batch_size: int
    learning_rate: float
    network_dim: int
    network_alpha: int


def count_images(dataset_dir: Path) -> int:
    """Count training images in dataset directory"""
    extensions = {".jpg", ".jpeg", ".png", ".webp"}
    count = 0

    for path in dataset_dir.rglob("*"):
        if path.suffix.lower() in extensions:
            count += 1

    return count


def calculate_optimal_params(
    num_images: int,
    model_type: str = "sdxl",
    target_steps: int = 2000,
    vram_gb: int = 24
) -> TrainingParams:
    """
    Calculate optimal training parameters based on dataset size.

    Args:
        num_images: Number of training images
        model_type: "sdxl" or "sd15"
        target_steps: Target total training steps
        vram_gb: Available VRAM in GB

    Returns:
        TrainingParams with calculated values
    """
    # Batch size based on VRAM
    if model_type == "sdxl":
        if vram_gb >= 24:
            batch_size = 2
        elif vram_gb >= 16:
            batch_size = 1
        else:
            batch_size = 1
    else:  # SD 1.5
        if vram_gb >= 16:
            batch_size = 4
        elif vram_gb >= 8:
            batch_size = 2
        else:
            batch_size = 1

    # Calculate repeats and epochs
    # Formula: total_steps = num_images * repeats * epochs / batch_size
    # Start with reasonable epochs
    if num_images < 50:
        num_epochs = 20
    elif num_images < 100:
        num_epochs = 15
    elif num_images < 200:
        num_epochs = 10
    elif num_images < 500:
        num_epochs = 8
    else:
        num_epochs = 6

    # Calculate repeats needed to hit target steps
    # steps_per_epoch = num_images * repeats / batch_size
    # total_steps = steps_per_epoch * num_epochs
    # repeats = (target_steps * batch_size) / (num_images * num_epochs)
    repeats = max(1, round((target_steps * batch_size) / (num_images * num_epochs)))

    # Recalculate actual total steps
    steps_per_epoch = (num_images * repeats) // batch_size
    total_steps = steps_per_epoch * num_epochs

    # Learning rate based on model type
    if model_type == "sdxl":
        learning_rate = 1e-4
        network_dim = 32
        network_alpha = 16
    else:
        learning_rate = 1e-4
        network_dim = 128
        network_alpha = 64

    return TrainingParams(
        num_images=num_images,
        total_steps=total_steps,
        num_epochs=num_epochs,
        repeats=repeats,
        batch_size=batch_size,
        learning_rate=learning_rate,
        network_dim=network_dim,
        network_alpha=network_alpha
    )


def generate_sdxl_config(
    dataset_dir: Path,
    output_dir: Path,
    character_name: str,
    params: TrainingParams,
    base_model: str = "/mnt/c/ai_models/checkpoints/waiANINSFWPONYXL_v90.safetensors",
    trigger_word: Optional[str] = None,
    class_token: str = "person"
) -> str:
    """Generate SDXL LoRA training TOML config"""

    trigger = trigger_word or character_name

    config = f'''# SDXL LoRA Training Configuration
# Character: {character_name}
# Generated: auto-generated by generate_kohya_config.py

[general]
enable_bucket = true
resolution = "1024,1024"
min_bucket_reso = 256
max_bucket_reso = 2048
bucket_reso_steps = 64

[sdxl_arguments]
cache_text_encoder_outputs = true
no_half_vae = true

[model_arguments]
pretrained_model_name_or_path = "{base_model}"
vae = ""

[dataset]
[[datasets]]
batch_size = {params.batch_size}
resolution = [1024, 1024]

[[datasets.subsets]]
image_dir = "{dataset_dir}"
class_tokens = "{trigger} {class_token}"
num_repeats = {params.repeats}
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 1
caption_dropout_rate = 0.0
caption_dropout_every_n_epochs = 0

[network_arguments]
network_module = "networks.lora"
network_dim = {params.network_dim}
network_alpha = {params.network_alpha}
network_dropout = 0
network_train_unet_only = false
network_train_text_encoder_only = false

[optimizer_arguments]
optimizer_type = "AdamW8bit"
learning_rate = {params.learning_rate}
unet_lr = {params.learning_rate}
text_encoder_lr = {params.learning_rate * 0.5}
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 100
lr_scheduler_num_cycles = 3

[training_arguments]
output_dir = "{output_dir}"
output_name = "{character_name}_lora_sdxl"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 2
save_last_n_epochs = 5
max_train_epochs = {params.num_epochs}
train_batch_size = {params.batch_size}
gradient_checkpointing = true
gradient_accumulation_steps = 1
mixed_precision = "bf16"
seed = 42
clip_skip = 2
max_token_length = 225
xformers = false
sdpa = true
cache_latents = true
cache_latents_to_disk = false
persistent_data_loader_workers = true
max_data_loader_n_workers = 4

[sample_prompt_arguments]
sample_every_n_epochs = 2
sample_sampler = "euler_a"
sample_prompts = """
{trigger} {class_token}, 3d animated character, pixar style, front view, neutral expression, studio lighting --n blurry, low quality, text, watermark --w 1024 --h 1024 --d 42 --l 7 --s 25
{trigger} {class_token}, 3d animated character, pixar style, three-quarter view, happy expression, warm lighting --n blurry, low quality, text, watermark --w 1024 --h 1024 --d 123 --l 7 --s 25
{trigger} {class_token}, 3d animated character, pixar style, close-up portrait, detailed face, soft lighting --n blurry, low quality, text, watermark --w 1024 --h 1024 --d 456 --l 7 --s 25
"""

[logging_arguments]
log_with = "tensorboard"
logging_dir = "{output_dir}/logs"
log_prefix = "{character_name}"

[additional_network_arguments]
no_metadata = false
'''

    return config


def generate_sd15_config(
    dataset_dir: Path,
    output_dir: Path,
    character_name: str,
    params: TrainingParams,
    base_model: str = "runwayml/stable-diffusion-v1-5",
    trigger_word: Optional[str] = None,
    class_token: str = "person"
) -> str:
    """Generate SD 1.5 LoRA training TOML config"""

    trigger = trigger_word or character_name

    config = f'''# SD 1.5 LoRA Training Configuration
# Character: {character_name}
# Generated: auto-generated by generate_kohya_config.py

[general]
enable_bucket = true
resolution = "512,512"
min_bucket_reso = 256
max_bucket_reso = 768
bucket_reso_steps = 64

[model_arguments]
pretrained_model_name_or_path = "{base_model}"
v2 = false
v_parameterization = false

[dataset]
[[datasets]]
batch_size = {params.batch_size}
resolution = [512, 512]

[[datasets.subsets]]
image_dir = "{dataset_dir}"
class_tokens = "{trigger} {class_token}"
num_repeats = {params.repeats}
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 1

[network_arguments]
network_module = "networks.lora"
network_dim = {params.network_dim}
network_alpha = {params.network_alpha}
network_dropout = 0

[optimizer_arguments]
optimizer_type = "AdamW8bit"
learning_rate = {params.learning_rate}
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 50
lr_scheduler_num_cycles = 3

[training_arguments]
output_dir = "{output_dir}"
output_name = "{character_name}_lora"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 2
max_train_epochs = {params.num_epochs}
train_batch_size = {params.batch_size}
gradient_checkpointing = true
mixed_precision = "fp16"
seed = 42
clip_skip = 2
max_token_length = 75
xformers = true
cache_latents = true

[sample_prompt_arguments]
sample_every_n_epochs = 2
sample_sampler = "euler_a"
sample_prompts = """
{trigger} {class_token}, 3d animated character, high quality --n blurry, low quality --w 512 --h 512 --d 42 --l 7 --s 25
"""

[logging_arguments]
log_with = "tensorboard"
logging_dir = "{output_dir}/logs"
'''

    return config


def main():
    parser = argparse.ArgumentParser(
        description="Generate Kohya LoRA Training Config",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Generate SDXL config
    python generate_kohya_config.py \\
        --dataset-dir /path/to/10_character \\
        --output-config /path/to/config.toml \\
        --character-name luca \\
        --model-type sdxl

    # Generate with custom parameters
    python generate_kohya_config.py \\
        --dataset-dir /path/to/training_data \\
        --output-config /path/to/config.toml \\
        --character-name miguel \\
        --model-type sdxl \\
        --target-steps 3000 \\
        --vram 16
        """
    )

    parser.add_argument("--dataset-dir", required=True, type=Path,
                        help="Training dataset directory")
    parser.add_argument("--output-config", required=True, type=Path,
                        help="Output TOML config path")
    parser.add_argument("--character-name", required=True,
                        help="Character name for trigger word")
    parser.add_argument("--model-type", default="sdxl",
                        choices=["sdxl", "sd15"],
                        help="Model type (default: sdxl)")
    parser.add_argument("--output-dir", type=Path, default=None,
                        help="Training output directory (default: dataset parent)")
    parser.add_argument("--base-model", default=None,
                        help="Base model path")
    parser.add_argument("--trigger-word", default=None,
                        help="Custom trigger word (default: character name)")
    parser.add_argument("--class-token", default="person",
                        help="Class token (default: person)")
    parser.add_argument("--target-steps", type=int, default=2000,
                        help="Target training steps (default: 2000)")
    parser.add_argument("--vram", type=int, default=24,
                        help="Available VRAM in GB (default: 24)")

    args = parser.parse_args()

    # Validate dataset directory
    if not args.dataset_dir.exists():
        print(f"Error: Dataset directory not found: {args.dataset_dir}")
        return 1

    # Count images
    num_images = count_images(args.dataset_dir)
    if num_images == 0:
        print(f"Error: No images found in {args.dataset_dir}")
        return 1

    print(f"Found {num_images} training images")

    # Calculate parameters
    params = calculate_optimal_params(
        num_images=num_images,
        model_type=args.model_type,
        target_steps=args.target_steps,
        vram_gb=args.vram
    )

    print(f"\nCalculated parameters:")
    print(f"  Repeats:       {params.repeats}")
    print(f"  Epochs:        {params.num_epochs}")
    print(f"  Batch size:    {params.batch_size}")
    print(f"  Total steps:   {params.total_steps}")
    print(f"  Learning rate: {params.learning_rate}")
    print(f"  Network dim:   {params.network_dim}")
    print(f"  Network alpha: {params.network_alpha}")

    # Output directory
    output_dir = args.output_dir or args.dataset_dir.parent / "output"

    # Generate config
    if args.model_type == "sdxl":
        base_model = args.base_model or "/mnt/c/ai_models/checkpoints/waiANINSFWPONYXL_v90.safetensors"
        config = generate_sdxl_config(
            dataset_dir=args.dataset_dir,
            output_dir=output_dir,
            character_name=args.character_name,
            params=params,
            base_model=base_model,
            trigger_word=args.trigger_word,
            class_token=args.class_token
        )
    else:
        base_model = args.base_model or "runwayml/stable-diffusion-v1-5"
        config = generate_sd15_config(
            dataset_dir=args.dataset_dir,
            output_dir=output_dir,
            character_name=args.character_name,
            params=params,
            base_model=base_model,
            trigger_word=args.trigger_word,
            class_token=args.class_token
        )

    # Save config
    args.output_config.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output_config, "w", encoding="utf-8") as f:
        f.write(config)

    print(f"\n✓ Config saved to: {args.output_config}")

    # Save summary
    summary = {
        "dataset_dir": str(args.dataset_dir),
        "num_images": num_images,
        "model_type": args.model_type,
        "character_name": args.character_name,
        "params": {
            "repeats": params.repeats,
            "epochs": params.num_epochs,
            "batch_size": params.batch_size,
            "total_steps": params.total_steps,
            "learning_rate": params.learning_rate,
            "network_dim": params.network_dim,
            "network_alpha": params.network_alpha
        }
    }

    summary_path = args.output_config.with_suffix(".json")
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    print(f"✓ Summary saved to: {summary_path}")

    return 0


if __name__ == "__main__":
    exit(main())
