#!/usr/bin/env bash
set -euo pipefail

# Run quality filtering (tiers A/B/C) for P3D multi-character synthetic data.
#
# Inputs (defaults match 2026-01-26/28 generation configs):
#   - generated_data_non_yokai_action_expression_100x5_20260126
#   - generated_data_non_yokai_pose_30x5_20260126
#
# Output:
#   - filtered_data_p3d_multichar_YYYYMMDD (default)
#
# Notes:
# - Requires `.png` images to have same-name `.txt` captions next to them
#   (generated by: scripts/batch/generate_p3d_tokenized_captions.py).

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DATA_ROOT="${DATA_ROOT:-/mnt/data/ai_data/synthetic_lora_data}"
CONDA_ENV="${CONDA_ENV:-ai_env}"

AE_DIR="${AE_DIR:-$DATA_ROOT/generated_data_non_yokai_action_expression_100x5_20260126}"
POSE_DIR="${POSE_DIR:-$DATA_ROOT/generated_data_non_yokai_pose_30x5_20260126}"

OUT_DIR="${OUT_DIR:-$DATA_ROOT/filtered_data_p3d_multichar_$(date +%Y%m%d)}"
NUM_WORKERS="${NUM_WORKERS:-0}"  # 0 = cpu_count
DEVICE="${DEVICE:-cpu}"

cd "$ROOT_DIR"

echo "[p3d-filter] start: $(date -Is)"
echo "[p3d-filter] ROOT_DIR=$ROOT_DIR"
echo "[p3d-filter] DATA_ROOT=$DATA_ROOT"
echo "[p3d-filter] CONDA_ENV=$CONDA_ENV"
echo "[p3d-filter] AE_DIR=$AE_DIR"
echo "[p3d-filter] POSE_DIR=$POSE_DIR"
echo "[p3d-filter] OUT_DIR=$OUT_DIR"
echo "[p3d-filter] NUM_WORKERS=$NUM_WORKERS DEVICE=$DEVICE"

mkdir -p "$OUT_DIR"

echo "[p3d-filter] step1: action+expression"
conda run -n "$CONDA_ENV" python scripts/generic/training/quality_filters/synthetic_quality_pipeline.py \
  --input-dir "$AE_DIR" \
  --output-dir "$OUT_DIR" \
  --lora-types action expression \
  --num-workers "$NUM_WORKERS" \
  --device "$DEVICE"

echo "[p3d-filter] step2: pose"
conda run -n "$CONDA_ENV" python scripts/generic/training/quality_filters/synthetic_quality_pipeline.py \
  --input-dir "$POSE_DIR" \
  --output-dir "$OUT_DIR" \
  --lora-types pose \
  --num-workers "$NUM_WORKERS" \
  --device "$DEVICE"

echo "[p3d-filter] done: $(date -Is)"

